from tkinter import *
top = Tk()
top.geometry('500x500+100-100')
# key=0
# while(key!=4):
#     print("Click 1 for size first : ")
#     print("Click 2 for size second :")
#     print("click 3 for size third :")
#     print("Enter the key from 1-3")
#     key = int(input("Enter the key "))
#     if(key==1):
#         top.geometry('500x500+100+100')
        
#     elif (key==2):
#         top.geometry('500x700+100+100')
        
#     elif(key==3):
#         top.geometry('700x800+100+100')
        

l1 = Label (text = "First name : ", font = ('tahoma',15,'bold'))
t1 = Entry(font=('tahoma',15,'bold'))
l2 = Label (text = "Last name :", font = ('tahoma',15,'bold'))
t2 = Entry(font=('tahoma',15,'bold'))
l3 = Label (text = "organaisation : ", font =('tahoma',15,'bold'))
t3 = Entry(font=('tahoma',15,'bold'))
l4 = Label (text = "Email Address : ", font = ('tahoma',15,'bold'))
t4 = Entry(font=('tahoma',15,'bold'))
l5 = Label (text = "Work phone : ", font = ('tahoma',15,'bold'))
t5 = Entry(font=('tahoma',15,'bold'))
l6 = Label (text = "Home phone : ", font = ('tahoma',15,'bold'))
t6 = Entry(font=('tahoma',15,'bold'))
l7 = Label (text = "Cell phone : ", font = ('tahoma',15,'bold'))
t7 = Entry(font=('tahoma',15,'bold'))
l8 = Label (text = "Fax :", font = ('tahoma',15,'bold'))
t8 = Entry(font=('tahoma',15,'bold'))
l9 = Label (text = "Address_1 :", font = ('tahoma',15,'bold'))
t9 = Entry(font=('tahoma',15,'bold'))
l10 = Label (text = "Address_2 :", font = ('tahoma',15,'bold'))
t10= Entry(font=('tahoma',15,'bold'))
l11= Label (text = "City*:", font = ('tahoma',15,'bold'))
t11= Entry(font=('tahoma',15,'bold'))
l12 = Label (text = "State/Province :", font = ('tahoma',15,'bold'))
t12= Entry(font=('tahoma',15,'bold'))
l13 = Label (text = "Zip Postal Code :", font = ('tahoma',15,'bold'))
t13 = Entry(font=('tahoma',15,'bold'))
l14 = Label (text = "Country* :", font = ('tahoma',15,'bold'))
t14 = Entry(font=('tahoma',15,'bold'))
l1.pack()
t1.pack()
l2.pack()
t2.pack()
l3.pack()
t3.pack()
l4.pack()
t4.pack()
l5.pack()
t5.pack()
l6.pack()
t6.pack()
l7.pack()
t7.pack()
l8.pack()
t8.pack()
l9.pack()
t9.pack()
l10.pack()
t10.pack()
l11.pack()
t11.pack()
l12.pack()
t12.pack()
l13.pack()
t13.pack()
l14.pack()
t14.pack()
      
top.mainloop()