from tkinter import *
top =Tk()
top.geometry('500x500+100+100')
l1 = Label(text = 'Enter your name ')
t1 = Entry(font=('tahoma',15,'bold'))
l2 = Label(text='Enter your email ')
t2 = Entry(font=('tahoma',15,'bold'))

l3 = Label(text = 'Your Gender',font=('tahoma',15,'bold'))
gen = IntVar()
rb1 = Radiobutton(text='Male',variable=gen,value=1)
rb2 = Radiobutton(text='Female',variable=gen,value=2)
rb3 = Radiobutton(text='Others',variable=gen,value=3)

l4 = Label(text = 'Language known :',font=('tahoma',15,'bold'))
chk1 = Checkbutton(text="English")
chk2 = Checkbutton(text='Hindi')
chk3 = Checkbutton(text="Marathi")
chk4 = Checkbutton(text="Gujarati")
chk5 = Checkbutton(text="Odia")
chk6 = Checkbutton(text="Tamil")

l1.pack()
t1.pack()
l2.pack()
t2.pack()
l3.pack()
rb1.pack()
rb2.pack()
rb3.pack()
l4.pack()
chk1.pack()
chk2.pack()
chk3.pack()
chk4.pack()
chk5.pack()
chk6.pack()

top.mainloop()
