from tkinter import *
top=Tk()
top.geometry('500x500+200+200')
l1 = Label(text='Employee Emergency Information ',font=('tahoma',30,'bold'))
l13 = Label(text='We will use these details only during emergency,Please give accurate information',font=('tahoma',10,'bold'))
l2 = Label(text='Name',font=('tahoma',10,'bold'))
t1 = Entry(font = ('San Serif',20,'bold'))
l3 = Label(text='Age*',font=('tahoma',10,'bold'))
t2 = Entry(font = ('San Serif',20,'bold'))
l4 = Label(text='Blood Group*',font=('tahoma',10,'bold'))
t3 = Entry(font = ('San Serif',20,'bold'))
l5 = Label(text='Emergency contact  number*',font=('tahoma',10,'bold'))
t4 = Entry(font = ('San Serif',20,'bold'))
l6 = Label(text='Do you have any long term illness ?*',font=('tahoma',10,'bold'))
key = IntVar()
rb1 = Radiobutton(text ='Yes',variable=key,value=1)
rb2 = Radiobutton(text ='No',variable=key,value=2)
l7 = Label(text='Do you have any medical insurance ?*',font=('tahoma',10,'bold'))
key = IntVar()
rb3 = Radiobutton(text ='Yes',variable=key,value=1)
rb4 = Radiobutton(text ='No',variable=key,value=2)
l8 = Label(text='Who is your insurance agent ?',font=('tahoma',10,'bold'))
t5 = Entry(font = ('San Serif',20,'bold'))
l9 = Label(text='Have your ever claimed insurance ?*',font=('tahoma',10,'bold'))
key = IntVar()
rb5 = Radiobutton(text ='Yes',variable=key,value=1)
rb6 = Radiobutton(text ='No',variable=key,value=2)
l10 = Label(text='Who is your nominee ?*',font=('tahoma',10,'bold'))
t6 = Entry(font = ('San Serif',20,'bold'))
l11 = Label(text='What is your insurance Company ?*',font=('tahoma',10,'bold'))
t7 = Entry(font = ('San Serif',20,'bold'))
l12 = Label(text='Have your undergone any surgery ?*',font=('tahoma',10,'bold'))
key = IntVar()
rb7 = Radiobutton(text ='Yes',variable=key,value=1)
rb8 = Radiobutton(text ='No',variable=key,value=2)
b = Button(font = ('tahoma',15,'bold'),width=20,border=30,background='black')
l1.pack()
l13.pack()
l2.pack()
t1.pack()
l3.pack()
t2.pack()
l4.pack()
t3.pack()
l5.pack()
t4.pack()
l6.pack()
rb1.pack()
rb2.pack()
l7.pack()
l3.pack()
l4.pack()
l8.pack()
t5.pack()
l9.pack()
rb5.pack()
rb6.pack()
l10.pack()
t6.pack()
l11.pack()
t7.pack()
l12.pack()
rb7.pack()
rb8.pack()
b.pack()


top.mainloop()